const WEAPONS_REQUEST = "WEAPONS_REQUEST";
const WEAPONS_SUCCESS = "WEAPONS_SUCCESS";
const WEAPONS_FAILURE = "WEAPONS_FAILURE";
const WEAPONS_ADD_WEAPONS = "WEAPONS_ADD_WEAPONS";
const WEAPONS_ADD = "WEAPONS_ADD";
const WEAPONS_DELETE = "WEAPONS_DELETE";
const WEAPONS_UPDATE = "WEAPONS_UPDATE";

const types = {
    WEAPONS_REQUEST,
    WEAPONS_ADD_WEAPONS,
    WEAPONS_ADD,
    WEAPONS_SUCCESS,
    WEAPONS_FAILURE,
    WEAPONS_DELETE,
    WEAPONS_UPDATE
}

export default types