const WARFRAMES_REQUEST = "WARFRAMES_REQUEST";
const WARFRAMES_SUCCESS = "WARFRAMES_SUCCESS";
const WARFRAMES_FAILURE = "WARFRAMES_FAILURE";
const WARFRAMES_ADD_WARFRAMES = "WARFRAMES_ADD_WARFRAMES";
const WARFRAMES_ADD = "WARFRAMES_ADD";
const WARFRAMES_DELETE = "WARFRAMES_DELETE";
const WARFRAMES_UPDATE = "WARFRAMES_UPDATE"

const types = {
    WARFRAMES_REQUEST,
    WARFRAMES_ADD_WARFRAMES,
    WARFRAMES_SUCCESS,
    WARFRAMES_FAILURE,
    WARFRAMES_ADD,
    WARFRAMES_DELETE,
    WARFRAMES_UPDATE
}

export default types